### ISSUE TITLE
Slow layer rendering

### ISSUE THREAD

**Issue by timlinux** [kartoza/least-cost-electrification-somaliland#4] opened 2021-09-13 14:20 UTC
![image](https://user-images.githubusercontent.com/178003/133100603-58f8e3a0-85e8-4804-bc47-ed5969d8c9e9.png)

https://somaliland.gep.kartoza.com/layers/geonode_data:geonode:Somaliland_WBPopulation_clusters_clipped0

**Comment by lkwalke4** [comment] 2021-09-20 16:42
@lucernae any luck looking into why the rendering of these Somaliland layers might be a bit slow?

**Comment by lucernae** [comment] 2021-09-22 12:59
Hi @lkwalke4 @timlinux , I can only observe it via browser. On average it needs less than 10 seconds to render a tile. I think this is slow. But I have no idea why, yet.

I could not measure objectively though, since the stack currently uses docker-compose and I can only have the network/cpu metric information if I deploy it via Kubernetes.
Perhaps we should allocate some time to migrate it to Rancher/K8s? But currently I don't know if this is a staging or production instance. IIRC, @meomancer deployed this directly in a dedicated Hetzner cloud in the past.

For clarity, I observe it using Network timing in the browser console. The green bars delay can be caused by network latency in the docker -> ingress itself or from GeoServer proxy. The blue bars are from my ISP (my ISP is very slow this week due to their network issue)

<img width="1668" alt="image" src="https://user-images.githubusercontent.com/831865/134344878-c6bed45f-aa8b-4810-b403-0664b4a107e1.png">

Some more network delay if I zoomed in to a dense cluster. I observed some tiles rendered almost one minute, but the green part is still less than 10 seconds, while the blue part has more delay (probably my ISP again and because the tiles are colorful now).

<img width="1660" alt="image" src="https://user-images.githubusercontent.com/831865/134345023-b3fa60c5-ded5-4f1d-bac6-5a94fd5d2a1e.png">

Besides that, I also noticed that for some reason the layer styling uses transparent color for the mid range. I thought the layer was not rendering correctly when I zoomed in, but it turns out that it renders transparent tiles when I zoomed in.

**Comment by lkwalke4** [comment] 2021-09-29 02:18
@lucernae any update here?

**Comment by meomancer** [comment] 2021-10-05 05:57
hi @seabilwe 
is this layer still needed?
becaise i think we already have 
https://somaliland.gep.kartoza.com/geoserver/geonode/wms?service=WMS&version=1.1.0&request=GetMap&layers=geonode%3ASomaliland_WBPopulation_clusters_clipped&bbox=42.7495831772076%2C8.00000000029985%2C49.0298871215608%2C11.4604168224619&width=768&height=423&srs=EPSG%3A4326&access_token=2bZH3FhiDxTRAa6aarjvHGeKgm4bN7&format=application/openlayers

this layer is Somaliland_WBPopulation_clusters_clipped0, with 0 in the end

NOTE:
The GEP is using Somaliland_WBPopulation_clusters_clipped without 0

**Comment by meomancer** [comment] 2021-10-05 06:04
and @timlinux @lucernae @lkwalke4 

this is not about slow rendering, but this is the image that coming from geoserver that is like that
you could see there is purple on the worqooyi (that is the layer that rendered)

could you help us to check why it renders like that @seabilwe 
maybe we can delete this layer and reuse Somaliland_WBPopulation_clusters_clipped?

https://somaliland.gep.kartoza.com/geoserver/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=geonode%3ASomaliland_WBPopulation_clusters_clipped0&STYLES=&SRS=EPSG%3A3857&CRS=EPSG%3A3857&TILED=true&access_token=2bZH3FhiDxTRAa6aarjvHGeKgm4bN7&WIDTH=256&HEIGHT=256&BBOX=4383204.9499851465%2C626172.1357121654%2C5009377.08569731%2C1252344.2714243294

**Comment by seabilwe** [comment] 2021-10-05 09:06
@meomancer the layer can be deleted, it's not used  in any map in the platform. I will remove it from the GeoNode side

**Comment by meomancer** [comment] 2021-10-07 03:02
The layer has been deleted, so i think we can close this ticket

**Closed by meomancer** 2021-10-07 03:02 UTC
